var json_GeoStops_1 = {
"type": "FeatureCollection",
"name": "GeoStops_1",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "STOP": "1", "LOCATION": "Walnut Creek Metropolitan Park", "COUNTY": "Travis", "TYPE": "CREEK EXPOSURE", "AGE": "K - lower", "FEATURE": "Walnut Formation", "DESCRIPTIO": "Fossiliferous Limestone Exposure", "Lat": 30.396075, "Long": -97.683986, "Picture": "https:\/\/cramos95.github.io\/GeologyPics\/Stop1.JPG" }, "geometry": { "type": "Point", "coordinates": [ -97.683985999700866, 30.396074998793704 ] } },
{ "type": "Feature", "properties": { "STOP": "2", "LOCATION": "Arboretum Blvd @ Renew Data Corp", "COUNTY": "Travis", "TYPE": "CUT", "AGE": "K-lower", "FEATURE": "Edwards Limestone", "DESCRIPTIO": "Clean exposure of Edwards with bioturbation at base and fossils, interesting bedding structures?", "Lat": 30.390599, "Long": -97.752614, "Picture": "https:\/\/cramos95.github.io\/GeologyPics\/Stop2.JPG" }, "geometry": { "type": "Point", "coordinates": [ -97.752614, 30.390599 ] } },
{ "type": "Feature", "properties": { "STOP": "3", "LOCATION": "Great Hills Corporate Center north off Loop 360", "COUNTY": "Travis", "TYPE": "ROADCUT", "AGE": "K - lower", "FEATURE": "Edwards Limestone", "DESCRIPTIO": "Vuggy limestone with rudist bivalve fossils", "Lat": 30.390164, "Long": -97.756165, "Picture": "https:\/\/cramos95.github.io\/GeologyPics\/Stop3.JPG" }, "geometry": { "type": "Point", "coordinates": [ -97.756165, 30.390164 ] } },
{ "type": "Feature", "properties": { "STOP": "4", "LOCATION": "Southbound Loop 360 @ Ranch Rd 2222, Austin", "COUNTY": "Travis", "TYPE": "ROADCUT", "AGE": "K-lower", "FEATURE": "Glen Rose, Quaternary Terrace Deposits", "Lat": 30.365914, "Long": -97.790186, "Picture": "https:\/\/cramos95.github.io\/GeologyPics\/Stop4.JPG" }, "geometry": { "type": "Point", "coordinates": [ -97.790186, 30.365914 ] } },
{ "type": "Feature", "properties": { "STOP": "5", "LOCATION": "Northbound Loop 360 @ Hwy 2244", "COUNTY": "Travis", "TYPE": "ROADCUT", "AGE": "K - lower", "FEATURE": "Walnut Formation, Bee Creek Member", "DESCRIPTIO": "Fossiliferous limestone exposure?", "Lat": 30.29702, "Long": -97.828641, "Picture": "https:\/\/cramos95.github.io\/GeologyPics\/Stop5.JPG" }, "geometry": { "type": "Point", "coordinates": [ -97.828641, 30.29702 ] } },
{ "type": "Feature", "properties": { "STOP": "6", "LOCATION": "Camp Creek Boat Ramp Road, off of 1431 West of Smithwick", "COUNTY": "Burnet", "TYPE": "CREEK EXPOSURE", "AGE": "IP", "FEATURE": "Smithwick Fm", "DESCRIPTIO": "Tall cut of dark gray shale, siltstone and sandstone.  Plant fossils, sole marks,  bedding features in float along cut.  Overlying Hensel\/Sycamore Sandstone crops out along road further up hill", "Lat": 30.565051, "Long": -98.188698, "Picture": "https:\/\/cramos95.github.io\/GeologyPics\/Stop6.JPG" }, "geometry": { "type": "Point", "coordinates": [ -98.188698, 30.565051 ] } },
{ "type": "Feature", "properties": { "STOP": "7", "LOCATION": "FM 1431 West of Marble Falls, Granite Mtn Roadside Rest Area", "COUNTY": "Burnet", "TYPE": "REST AREA", "AGE": "IP", "FEATURE": "Marble Falls limestone, Lower Pennsylvanian Smithwick fm & Proterozoic Town Mountain Granite", "DESCRIPTIO": "Samples of Marble Falls Limestone and Smithwick Fm located in picnic area; picnic tables made of polished slabs of Town Mountain Granite", "Lat": 30.592611, "Long": -98.29895, "Picture": "https:\/\/cramos95.github.io\/GeologyPics\/Stop7.JPG" }, "geometry": { "type": "Point", "coordinates": [ -98.29895, 30.592611 ] } },
{ "type": "Feature", "properties": { "STOP": "8", "LOCATION": "FM 2341, approx. 5 mi from Hwy 29 intersection", "COUNTY": "Burnet", "TYPE": "ROADCUT", "AGE": "pC", "FEATURE": "Valley Springs Gneiss w\/ pegmatite dike", "DESCRIPTIO": "Giant K-spar and euhedral biottie, good cross-cutting relationships", "Lat": 30.808464, "Long": -98.333763, "Picture": "https:\/\/cramos95.github.io\/GeologyPics\/Stop8.JPG" }, "geometry": { "type": "Point", "coordinates": [ -98.333763, 30.808464 ] } },
{ "type": "Feature", "properties": { "STOP": "9", "LOCATION": "FM 2341 approx 7 mi from Hwy 29", "COUNTY": "Burnet", "TYPE": "ROADCUT", "AGE": "C", "FEATURE": "Lion Mtn Formation", "DESCRIPTIO": "Small exposure of glauconitic calcareous sandstone and carbonate lenses", "Lat": 30.845076, "Long": -98.34873, "Picture": "https:\/\/cramos95.github.io\/GeologyPics\/Stop9.JPG" }, "geometry": { "type": "Point", "coordinates": [ -98.34873, 30.845076 ] } },
{ "type": "Feature", "properties": { "STOP": "10", "LOCATION": "FM 2341, approx. 9 mi from Hwy 29 intersection", "COUNTY": "Burnet", "TYPE": "ROADCUT", "AGE": "C", "FEATURE": "Hickory Sandstone, Riley Formation", "DESCRIPTIO": "hemaitte cement sandstone with thin shale layers, well rounded qtz grains, obvious normal fault, trace fossils, ripple marks", "Lat": 30.842645, "Long": -98.364415, "Picture": "https:\/\/cramos95.github.io\/GeologyPics\/Stop10.JPG" }, "geometry": { "type": "Point", "coordinates": [ -98.364415, 30.842645 ] } },
{ "type": "Feature", "properties": { "STOP": "11", "LOCATION": "Hoover Point \/ Lake LBJ Lookout & Rest Area, FM 1431 east of Kingsland", "COUNTY": "Burnet", "TYPE": "ROADCUT", "AGE": "C", "FEATURE": "Lion Mtn Formation", "DESCRIPTIO": "Well-exposed glauconitic sandstone, normal faults and cross-bedding visible on road cut.  NO Cut access - too dangerous, but samples of rock available in parking area.", "Lat": 30.645182, "Long": -98.415812, "Picture": "https:\/\/cramos95.github.io\/GeologyPics\/Stop11.JPG" }, "geometry": { "type": "Point", "coordinates": [ -98.415812, 30.645182 ] } },
{ "type": "Feature", "properties": { "STOP": "12", "LOCATION": "Babyhead Ridge, Hwy 16, 8 mi north of Llano", "COUNTY": "Llano", "TYPE": "ROADCUT", "AGE": "pC", "FEATURE": "Llanite dikel with K-spar and \"blue\" quartz phenocrysts", "DESCRIPTIO": "Exposure of unique rock found only in texas.  Famous for bluish quartz phenocrysts.", "Lat": 30.890722, "Long": -98.658526, "Picture": "https:\/\/cramos95.github.io\/GeologyPics\/Stop12.JPG" }, "geometry": { "type": "Point", "coordinates": [ -98.445764, 30.740519 ] } },
{ "type": "Feature", "properties": { "STOP": "13", "LOCATION": "Hwy 71 @ Honey Creek, south of Llano", "COUNTY": "Llano", "TYPE": "ROADCUT", "AGE": "pC", "FEATURE": "Packsaddle Schist", "DESCRIPTIO": "Foliated graphitic schist, small exposure of marble at eastern end of southern cut, change of foliation orientation across road caused by faulting (fault not visible)", "Lat": 30.630205, "Long": -98.528907, "Picture": "https:\/\/cramos95.github.io\/GeologyPics\/Stop13.JPG" }, "geometry": { "type": "Point", "coordinates": [ -98.528907, 30.630205 ] } }
]
}
